### ISSUE TITLE
TypeError: Argument `fetch` = None has invalid type “NoneType“. Cannot be None

### ISSUE THREAD

**Issue by isMoJo** [PhonemeHallucinator/Phoneme_Hallucinator#1]
Hello author, I have a question to ask：
    I installed the environment according to the requirements.txt, but it was prompted that the numpy version did not match. If it matches, I need to upgrade tf to version 2. But the code needs to be changed to be compatible with tf1. When running run.py, an error will be reported. Can you help me answer it? Thank you very much!
error：
![图片1](https://github.com/PhonemeHallucinator/Phoneme_Hallucinator/assets/49431152/36744f1f-a7cf-469d-9873-fa0a91b6ea3e)
and I found the summ==None

**Comment by isMoJo** [comment]
Reinstalled the environment and now there are no problems, but new problems were discovered，Ask for helpo(╥﹏╥)o



2024-02-21 08:43:12.238447: E tensorflow/core/kernels/check_numerics_op.cc:199] abnormal_detected_host @0x7f560a99bb00 = {0, 1} Gradient norm is NaN or Inf.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values
	 [[{{node CheckNumerics}}]]
	 [[CheckNumerics/_677]]
  (1) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values
	 [[{{node CheckNumerics}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/run.py", line 61, in <module>
    runner.run()
  File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/runner.py", line 107, in run
    train_metric = self.train()
  File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/runner.py", line 28, in train
    metric, summ, step, _ = self.model.execute(
  File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/base.py", line 103, in execute
    return self.sess.run(cmd, {self.x:batch['x'], self.b:batch['b'], self.m:batch['m']})
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 955, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1179, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values
	 [[node CheckNumerics (defined at /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[CheckNumerics/_677]]
  (1) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values
	 [[node CheckNumerics (defined at /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'CheckNumerics':
  File "scripts/run.py", line 55, in <module>
    model = get_model(params)
  File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/__init__.py", line 5, in get_model
    model = ACSetVAE(hps)
  File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/pc_acset_vae.py", line 19, in __init__
    super(ACSetVAE, self).__init__(hps)
  File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/base.py", line 20, in __init__
    self.build_ops()
  File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/base.py", line 92, in build_ops
    gradient_norm = tf.check_numerics(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1010, in check_numerics
    _, _, _op = _op_def_lib._apply_op_helper(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 792, in _apply_op_helper
    op = g.create_op(op_type_name, inputs, dtypes=None, name=scope,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/util/deprecation.py", line 513, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 3356, in create_op
    return self._create_op_internal(op_type, inputs, dtypes, input_types, name,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 3418, in _create_op_internal
    ret = Operation(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by shansiliu95** [comment]
> Reinstalled the environment and now there are no problems, but new problems were discovered，Ask for helpo(╥﹏╥)o
> 
> 2024-02-21 08:43:12.238447: E tensorflow/core/kernels/check_numerics_op.cc:199] abnormal_detected_host @0x7f560a99bb00 = {0, 1} Gradient norm is NaN or Inf. Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call return fn(*args) File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1349, in _run_fn return self._call_tf_sessionrun(options, feed_dict, fetch_list, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1441, in _call_tf_sessionrun return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict, tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found. (0) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values [[{{node CheckNumerics}}]] [[CheckNumerics/_677]] (1) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values [[{{node CheckNumerics}}]] 0 successful operations. 0 derived errors ignored.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "scripts/run.py", line 61, in runner.run() File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/runner.py", line 107, in run train_metric = self.train() File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/runner.py", line 28, in train metric, summ, step, _ = self.model.execute( File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/base.py", line 103, in execute return self.sess.run(cmd, {self.x:batch['x'], self.b:batch['b'], self.m:batch['m']}) File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 955, in run result = self._run(None, fetches, feed_dict, options_ptr, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1179, in _run results = self._do_run(handle, final_targets, final_fetches, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1358, in _do_run return self._do_call(_run_fn, feeds, fetches, targets, options, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call raise type(e)(node_def, op, message) tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found. (0) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values [[node CheckNumerics (defined at /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]] [[CheckNumerics/_677]] (1) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values [[node CheckNumerics (defined at /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]] 0 successful operations. 0 derived errors ignored.
> 
> Original stack trace for 'CheckNumerics': File "scripts/run.py", line 55, in model = get_model(params) File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/**init**.py", line 5, in get_model model = ACSetVAE(hps) File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/pc_acset_vae.py", line 19, in **init** super(ACSetVAE, self).**init**(hps) File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/base.py", line 20, in **init** self.build_ops() File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/base.py", line 92, in build_ops gradient_norm = tf.check_numerics( File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1010, in check_numerics _, _, _op = _op_def_lib._apply_op_helper( File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 792, in _apply_op_helper op = g.create_op(op_type_name, inputs, dtypes=None, name=scope, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/util/deprecation.py", line 513, in new_func return func(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 3356, in create_op return self._create_op_internal(op_type, inputs, dtypes, input_types, name, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 3418, in _create_op_internal ret = Operation( File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in **init** self._traceback = tf_stack.extract_stack()


> Reinstalled the environment and now there are no problems, but new problems were discovered，Ask for helpo(╥﹏╥)o
> 
> 2024-02-21 08:43:12.238447: E tensorflow/core/kernels/check_numerics_op.cc:199] abnormal_detected_host @0x7f560a99bb00 = {0, 1} Gradient norm is NaN or Inf. Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call return fn(*args) File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1349, in _run_fn return self._call_tf_sessionrun(options, feed_dict, fetch_list, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1441, in _call_tf_sessionrun return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict, tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found. (0) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values [[{{node CheckNumerics}}]] [[CheckNumerics/_677]] (1) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values [[{{node CheckNumerics}}]] 0 successful operations. 0 derived errors ignored.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "scripts/run.py", line 61, in runner.run() File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/runner.py", line 107, in run train_metric = self.train() File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/runner.py", line 28, in train metric, summ, step, _ = self.model.execute( File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/base.py", line 103, in execute return self.sess.run(cmd, {self.x:batch['x'], self.b:batch['b'], self.m:batch['m']}) File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 955, in run result = self._run(None, fetches, feed_dict, options_ptr, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1179, in _run results = self._do_run(handle, final_targets, final_fetches, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1358, in _do_run return self._do_call(_run_fn, feeds, fetches, targets, options, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call raise type(e)(node_def, op, message) tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found. (0) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values [[node CheckNumerics (defined at /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]] [[CheckNumerics/_677]] (1) Invalid argument: Gradient norm is NaN or Inf. : Tensor had Inf values [[node CheckNumerics (defined at /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]] 0 successful operations. 0 derived errors ignored.
> 
> Original stack trace for 'CheckNumerics': File "scripts/run.py", line 55, in model = get_model(params) File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/**init**.py", line 5, in get_model model = ACSetVAE(hps) File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/pc_acset_vae.py", line 19, in **init** super(ACSetVAE, self).**init**(hps) File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/base.py", line 20, in **init** self.build_ops() File "/mnt/v1/home/yulimei/investigationAndResearchModel/Phoneme_Hallucinator_2/Phoneme_Hallucinator/models/base.py", line 92, in build_ops gradient_norm = tf.check_numerics( File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1010, in check_numerics _, _, _op = _op_def_lib._apply_op_helper( File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 792, in _apply_op_helper op = g.create_op(op_type_name, inputs, dtypes=None, name=scope, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/util/deprecation.py", line 513, in new_func return func(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 3356, in create_op return self._create_op_internal(op_type, inputs, dtypes, input_types, name, File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 3418, in _create_op_internal ret = Operation( File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in **init** self._traceback = tf_stack.extract_stack()

Hi,

I also encounter this Nan issue when developing this model. My strategy is to rerun the training multiple times with different seeds.

**Comment by lareina-a** [comment]
> 您好作者，我有一个问题要问：我根据requirements.txt安装了环境，但提示numpy版本不匹配。如果匹配，我需要将 tf 升级到版本 2。但是需要更改代码才能与 tf1 兼容。运行 run.py 时，将报告错误。你能帮我回答吗？谢谢！错误：![图片1](https://private-user-images.githubusercontent.com/49431152/306545060-36744f1f-a7cf-469d-9873-fa0a91b6ea3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjMzNTMsIm5iZiI6MTcxODUyMzA1MywicGF0aCI6Ii80OTQzMTE1Mi8zMDY1NDUwNjAtMzY3NDRmMWYtYTdjZi00NjlkLTk4NzMtZmEwYTkxYjZlYTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA3MzA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OTc4ZThlOTI5NjAwYmE3YmVlNzI5YTI1ZDEyNTQ0YzUxYzViZDVkNmNlMjYxYmY3OWI0MGNhNWI0OWIwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U7I7-Xuf2KFrOv0WaZg_YAhfm7GfZNrfPONsvC8lQpA)我找到了summ==None
Hello,can you share the code you changed?我将 tf 升级到版本 2，怎么更改代码才能与 tf1 兼容，我没有调出来

**Comment by lareina-a** [comment]
我将 tf 升级到版本 2，怎么更改代码才能与 tf1 兼容，我没有调出来，可以分享一下吗
